version: '3'

services:
  db:
    image: mysql:5.7
    container_name: delivery-app-database
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./database:/db
    networks:
      database:
  api:
    build: .
    container_name: delivery-app-api
    depends_on:
      - db
    restart: always
    ports:
      - 3001:3001
    environment:
      - API_PORT=3001
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - HOSTNAME=db
      - MYSQL_PASSWORD=root
      - MYSQL_DB_NAME=delivery-app
      - NODE_ENV=development
    volumes:
      - ./:/app-backend
      - /node_modules
    networks:
      database:
      api:
networks:
  database:
  api:
